-- begin KPISAMPLE_ACHIEVEMENT
alter table KPISAMPLE_ACHIEVEMENT add constraint FK_KPISAMPLE_ACHIEVEMENT_ON_KPI foreign key (KPI_ID) references KPISAMPLE_KPI(ID)^
alter table KPISAMPLE_ACHIEVEMENT add constraint FK_KPISAMPLE_ACHIEVEMENT_ON_TASK foreign key (TASK_ID) references KPISAMPLE_TASK(ID)^
create index IDX_KPISAMPLE_ACHIEVEMENT_ON_KPI on KPISAMPLE_ACHIEVEMENT (KPI_ID)^
create index IDX_KPISAMPLE_ACHIEVEMENT_ON_TASK on KPISAMPLE_ACHIEVEMENT (TASK_ID)^
-- end KPISAMPLE_ACHIEVEMENT
-- begin KPISAMPLE_TASK
alter table KPISAMPLE_TASK add constraint FK_KPISAMPLE_TASK_ON_KPI foreign key (KPI_ID) references KPISAMPLE_KPI(ID)^
create index IDX_KPISAMPLE_TASK_ON_KPI on KPISAMPLE_TASK (KPI_ID)^
-- end KPISAMPLE_TASK
