alter table KPISAMPLE_ACHIEVEMENT add constraint FK_KPISAMPLE_ACHIEVEMENT_ON_TASK foreign key (TASK_ID) references KPISAMPLE_TASK(ID);
create index IDX_KPISAMPLE_ACHIEVEMENT_ON_TASK on KPISAMPLE_ACHIEVEMENT (TASK_ID);
